/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indeks;

import florist.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NDR
 */
public class padmin extends javax.swing.JPanel {
    Connection conn = new koneksi().conn();
    DefaultTableModel model;
    int ID;

    /**
     * Creates new form padmin
     */
    public padmin() {
        initComponents();
        tampil();
        lbl_id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_admin_user = new javax.swing.JTextField();
        tf_admin_pass = new javax.swing.JTextField();
        btn_admin_ubah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_admin = new javax.swing.JTable();
        btn_admin_tambah = new javax.swing.JButton();
        btn_admin_hapus = new javax.swing.JButton();
        btn_admin_reset = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Admin");

        jLabel1.setText("Username");

        jLabel3.setText("Password");

        btn_admin_ubah.setText("UBAH");
        btn_admin_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_ubahActionPerformed(evt);
            }
        });

        tbl_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_adminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_admin);

        btn_admin_tambah.setText("TAMBAH");
        btn_admin_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_tambahActionPerformed(evt);
            }
        });

        btn_admin_hapus.setText("HAPUS");
        btn_admin_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_hapusActionPerformed(evt);
            }
        });

        btn_admin_reset.setText("REFRESH");
        btn_admin_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_admin_user)
                            .addComponent(tf_admin_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_admin_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_admin_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_admin_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_admin_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_admin_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_admin_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_admin_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_admin_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_admin_ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_admin_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_admin_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_ubahActionPerformed
        try {
            String sqlubah = "UPDATE user SET username=?,pass=? WHERE id_user=?";
            PreparedStatement ps = conn.prepareStatement(sqlubah);
            ps.setString(1, tf_admin_user.getText());
            ps.setString(2, tf_admin_pass.getText());
            ps.setString(3, lbl_id.getText());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Edit Berhasil");
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(padmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_admin_ubahActionPerformed

    private void btn_admin_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_tambahActionPerformed
        try {
            String sqltambah = "INSERT INTO user(username,pass) VALUES (?,?)";
            PreparedStatement ps=conn.prepareStatement(sqltambah);
            ps.setString(1, tf_admin_user.getText());
            ps.setString(2, tf_admin_pass.getText());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Input Berhasil");
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(padmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_admin_tambahActionPerformed

    private void tbl_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_adminMouseClicked
        int i = tbl_admin.getSelectedRow();
        if(i>-1){
            lbl_id.setText(model.getValueAt(i, 0).toString());
            tf_admin_user.setText(model.getValueAt(i, 1).toString());
            tf_admin_pass.setText(model.getValueAt(i, 2).toString());
        }
    }//GEN-LAST:event_tbl_adminMouseClicked

    private void btn_admin_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_hapusActionPerformed
        try {
            String sqlhapus ="DELETE FROM user WHERE id_user='"+lbl_id.getText()+"'";
            conn.createStatement().executeUpdate(sqlhapus);
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(padmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_admin_hapusActionPerformed

    private void btn_admin_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_admin_resetActionPerformed


    public void tampil(){
        try {
            String [] head_tbl ={"ID","USERNAME","PASSWORD"};
            model = new DefaultTableModel(head_tbl,0);
            tbl_admin.setModel(model);
            
            int row = tbl_admin.getRowCount();
            for (int i=1;i<row;i++){
                model.removeRow(0);
            }
            String sqltampil = "SELECT * FROM user";
            ResultSet rs = conn.createStatement().executeQuery(sqltampil);
            while(rs.next()){
                String [] data = {rs.getString(1),rs.getString(2),rs.getString(3)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(padmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void reset(){
        tf_admin_user.setText("");
        tf_admin_pass.setText("");
        tampil();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin_hapus;
    private javax.swing.JButton btn_admin_reset;
    private javax.swing.JButton btn_admin_tambah;
    private javax.swing.JButton btn_admin_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tbl_admin;
    private javax.swing.JTextField tf_admin_pass;
    private javax.swing.JTextField tf_admin_user;
    // End of variables declaration//GEN-END:variables
}
