/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indeks;

import florist.koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author NDR
 */
public class pstatus extends javax.swing.JPanel {
    Connection conn = new koneksi().conn();
    DefaultTableModel model;
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    Map<String, Object> param=new HashMap<String, Object>();
    String batas1 = null;
    String batas2 = null;
    

    /**
     * Creates new form pstatus
     */
    public pstatus() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_stat = new javax.swing.JTable();
        btn_stat_sjalan = new javax.swing.JButton();
        btn_stat_fpesan = new javax.swing.JButton();
        btn_stat_laporan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_stat_ubah = new javax.swing.JButton();
        btn_stat_hapus = new javax.swing.JButton();
        btn_stat_cek = new javax.swing.JButton();
        tf_stat_cari = new javax.swing.JTextField();
        btn_stat_cari = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Status");

        tbl_stat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_stat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_statMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_stat);

        btn_stat_sjalan.setText("SURAT JALAN");
        btn_stat_sjalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stat_sjalanActionPerformed(evt);
            }
        });

        btn_stat_fpesan.setText("FORM PESANAN");
        btn_stat_fpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stat_fpesanActionPerformed(evt);
            }
        });

        btn_stat_laporan.setText("LAPORAN");
        btn_stat_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stat_laporanActionPerformed(evt);
            }
        });

        jLabel2.setText("BUAT");

        btn_stat_ubah.setText("UBAH");
        btn_stat_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stat_ubahActionPerformed(evt);
            }
        });

        btn_stat_hapus.setText("HAPUS");
        btn_stat_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stat_hapusActionPerformed(evt);
            }
        });

        btn_stat_cek.setText("CEK");
        btn_stat_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stat_cekActionPerformed(evt);
            }
        });

        tf_stat_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_stat_cariActionPerformed(evt);
            }
        });

        btn_stat_cari.setText("CARI");
        btn_stat_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stat_cariActionPerformed(evt);
            }
        });

        jLabel3.setText("ID :");

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btn_stat_cek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_stat_ubah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_stat_hapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btn_stat_laporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_stat_sjalan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_stat_fpesan, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 630, Short.MAX_VALUE)
                                .addComponent(tf_stat_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_stat_cari)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_stat_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_stat_cari))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_stat_cek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_stat_ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_stat_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_stat_sjalan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_stat_fpesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_stat_laporan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_stat_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_stat_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_stat_cariActionPerformed

    private void btn_stat_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stat_cekActionPerformed
        if(lbl_id.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Klik Table Dahulu");
        } else {
            stat_cek cek = new stat_cek();
            cek.setVisible(true);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            cek.setLocation(dim.width/2-cek.getSize().width/2, dim.height/2-cek.getSize().height/2);
            cek.aktifasi(false);
            cek.getid(lbl_id.getText());
            String sqltampil = "SELECT nama_pesan,telp_pesan,alamat_pesan,alamat_tujuan,konten,stat_pesan,pesan.kd_bunga,alamat_tagih,status_pembayaran,harga FROM pesan,bayar,bunga WHERE pesan.id_pesan=bayar.id_pesan AND pesan.kd_bunga=bunga.kd_bunga AND pesan.id_pesan=?";
            try {
                PreparedStatement ps = conn.prepareStatement(sqltampil);
                ps.setString(1, lbl_id.getText());
                ResultSet rs = ps.executeQuery();
                rs.next();
                String nama = rs.getString("nama_pesan");
                cek.getnama(nama);
                String telp = rs.getString("telp_pesan");
                cek.gettpesan(telp);
                String apesan = rs.getString("alamat_pesan");
                cek.getapesan(apesan);
                String atujuan = rs.getString("alamat_tujuan");
                cek.getatujuan(atujuan);
                String konten = rs.getString("konten");
                cek.getkonten(konten);
                String statpesan = rs.getString("stat_pesan");
                cek.getstatpesan(statpesan);
                String kd = rs.getString("pesan.kd_bunga");
                cek.getkdbunga(kd);
                String tagih = rs.getString("alamat_tagih");
                cek.getatagih(tagih);
                String sbayar = rs.getString("status_pembayaran");
                cek.getstatusbayar(sbayar);
                String harga = rs.getString("harga");
                cek.getharga(harga);
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(pstatus.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btn_stat_cekActionPerformed

    private void btn_stat_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stat_ubahActionPerformed
        if(lbl_id.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Klik Table Dahulu");
        } else {
            stat_cek cek = new stat_cek();
            cek.setVisible(true);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            cek.setLocation(dim.width/2-cek.getSize().width/2, dim.height/2-cek.getSize().height/2);
            cek.aktifasi(true);
            cek.getid(lbl_id.getText());
            String sqltampil = "SELECT nama_pesan,telp_pesan,alamat_pesan,alamat_tujuan,konten,stat_pesan,pesan.kd_bunga,alamat_tagih,status_pembayaran,harga FROM pesan,bayar,bunga WHERE pesan.id_pesan=bayar.id_pesan AND pesan.kd_bunga=bunga.kd_bunga AND pesan.id_pesan=?";
            try {
                PreparedStatement ps = conn.prepareStatement(sqltampil);
                ps.setString(1, lbl_id.getText());
                ResultSet rs = ps.executeQuery();
                rs.next();
                String nama = rs.getString("nama_pesan");
                cek.getnama(nama);
                String telp = rs.getString("telp_pesan");
                cek.gettpesan(telp);
                String apesan = rs.getString("alamat_pesan");
                cek.getapesan(apesan);
                String atujuan = rs.getString("alamat_tujuan");
                cek.getatujuan(atujuan);
                String konten = rs.getString("konten");
                cek.getkonten(konten);
                String statpesan = rs.getString("stat_pesan");
                cek.getstatpesan(statpesan);
                String kd = rs.getString("pesan.kd_bunga");
                cek.getkdbunga(kd);
                String tagih = rs.getString("alamat_tagih");
                cek.getatagih(tagih);
                String sbayar = rs.getString("status_pembayaran");
                cek.getstatusbayar(sbayar);
                String harga = rs.getString("harga");
                cek.getharga(harga);
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(pstatus.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btn_stat_ubahActionPerformed

    private void tbl_statMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_statMouseClicked
        int i = tbl_stat.getSelectedRow();
        if(i>-1){
            lbl_id.setText(model.getValueAt(i, 0).toString());
            
            
        }
    }//GEN-LAST:event_tbl_statMouseClicked

    private void btn_stat_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stat_hapusActionPerformed
        try {
            String sqlhapus = "DELETE FROM pesan WHERE id_pesan=?";
            PreparedStatement ps = conn.prepareStatement(sqlhapus);
            ps.setString(1, lbl_id.getText());
            ps.executeUpdate();
            String bsqlhapus ="DELETE FROM bayar WHERE id_pesan=?";
            PreparedStatement ps1 = conn.prepareStatement(bsqlhapus);
            ps1.setString(1, lbl_id.getText());
            ps1.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Berhasil Terhapus");
            tampil();
        } catch (SQLException ex) {
            Logger.getLogger(pstatus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_stat_hapusActionPerformed

    private void btn_stat_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stat_laporanActionPerformed
        lapor();
    }//GEN-LAST:event_btn_stat_laporanActionPerformed

    private void btn_stat_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stat_cariActionPerformed
        try {
            String [] head_tbl = {"ID Pemesanan","Nama Pemesan","Biaya","Tgl Pesan","Tgl Kirim","Tgl Bayar","Nama Tujuan","Pembayaran"};
            model = new DefaultTableModel(head_tbl, 0);
            tbl_stat.setModel(model);
            int row = tbl_stat.getRowCount();
            for (int i=1;i<row;i++){
                model.removeRow(0);
            }
            String sql_stat_tampil = "SELECT pesan.id_pesan, pesan.nama_pesan, bunga.harga, pesan.tgl_pesan, pesan.tgl_kirim, bayar.tgl_bayar, pesan.stat_pesan, bayar.status_pembayaran"
                    + "               FROM pesan,bunga,bayar "
                    + "               WHERE pesan.id_pesan=bayar.id_pesan AND pesan.kd_bunga=bunga.kd_bunga "
                    + "               AND (pesan.id_pesan=? OR pesan.nama_pesan=? OR pesan.tgl_pesan=? OR pesan.tgl_kirim=? "
                    + "               OR bayar.tgl_bayar=? OR pesan.stat_pesan=? OR bayar.status_pembayaran=?) "
                    + "               GROUP BY pesan.id_pesan ORDER BY pesan.id_pesan";
            
            PreparedStatement ps = conn.prepareStatement(sql_stat_tampil);
            ps.setString(1, tf_stat_cari.getText());
            ps.setString(2, tf_stat_cari.getText());
            ps.setString(3, tf_stat_cari.getText());
            ps.setString(4, tf_stat_cari.getText());
            ps.setString(5, tf_stat_cari.getText());
            ps.setString(6, tf_stat_cari.getText());
            ps.setString(7, tf_stat_cari.getText());
            ResultSet rss = ps.executeQuery();
            while(rss.next()){
                String data[] = {rss.getString(1),rss.getString(2),rss.getString(3),rss.getString(4),rss.getString(5),rss.getString(6),rss.getString(7),rss.getString(8)};
                model.addRow(data);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(pstatus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_stat_cariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_stat_fpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stat_fpesanActionPerformed
        if(lbl_id.getText().equals(null)){
        JOptionPane.showMessageDialog(null,"Klik Data Yg ingin Dicetak");
        }else{
        pesan();
        }
    }//GEN-LAST:event_btn_stat_fpesanActionPerformed

    private void btn_stat_sjalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stat_sjalanActionPerformed
        if(lbl_id.getText().equals(null)){
        JOptionPane.showMessageDialog(null,"Klik Data Yg ingin Dicetak");
        }else{
        surat_jalan();
        }
    }//GEN-LAST:event_btn_stat_sjalanActionPerformed


    public void tampil(){
        String [] head_tbl = {"ID Pemesanan","Nama Pemesan","Biaya","Tgl Pesan","Tgl Kirim","Tgl Bayar","Nama Tujuan","Pembayaran"};
        model = new DefaultTableModel(head_tbl, 0);
        tbl_stat.setModel(model);
        int row = tbl_stat.getRowCount();
        for (int i=1;i<row;i++){
            model.removeRow(0);
        }
        String sql_stat_tampil = "SELECT pesan.id_pesan, pesan.nama_pesan, bunga.harga, pesan.tgl_pesan, pesan.tgl_kirim, bayar.tgl_bayar, pesan.stat_pesan, bayar.status_pembayaran"
                + "               FROM pesan,bunga,bayar "
                + "               WHERE pesan.id_pesan=bayar.id_pesan AND pesan.kd_bunga=bunga.kd_bunga "
                + "               GROUP BY pesan.id_pesan ORDER BY pesan.id_pesan";
        try {
            ResultSet rss = conn.createStatement().executeQuery(sql_stat_tampil);
            while(rss.next()){
                String data[] = {rss.getString(1),rss.getString(2),rss.getString(3),rss.getString(4),rss.getString(5),rss.getString(6),rss.getString(7),rss.getString(8)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(pstatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void reset(){
        tf_stat_cari.setText("");
        this.setVisible(false);
        this.setVisible(true);
        tampil();
    }
    
    public void lapor(){
        if(batas1 == null || batas2 == null){
            laporan lap = new laporan();
            lap.setVisible(true);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            lap.setLocation(dim.width/2-lap.getSize().width/2, dim.height/2-lap.getSize().height/2);
        } 
        else{
        try {
            InputStream f = getClass().getResourceAsStream("/report/laporanbulan.jrxml");
            //File f=new File("src/report/laporanbulan.jrxml");
            jasperDesign = JRXmlLoader.load(f);
            //param.clear();
            //param.put("nama", tf_crud_cetak.getText());
            param.put("parameter1", batas1);
            param.put("parameter2", batas2);
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, conn);
            jasperPrint.setName("Laporan Bulanan");
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(pstatus.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    }    
    public void pesan(){
        
        try {
            InputStream f = getClass().getResourceAsStream("/report/formpesan.jrxml");
            //File f=new File("src/report/formpesan.jrxml");
            jasperDesign = JRXmlLoader.load(f);
            //param.clear();
            //Locale locale = new java.util.Locale("id","ID","id-ID");
            //param.put("mydate", new SimpleDateFormat("EEEEE dd MMMMM yyyy", locale).format(new Date()));
            param.put("pesan.id_pesan", lbl_id.getText());
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, conn);
            jasperPrint.setName("Lembar Pemesanan");
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(pstatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    public void surat_jalan(){
        
        try {
            InputStream f = getClass().getResourceAsStream("/report/suratjalan.jrxml");
            //File f=new File("src/report/suratjalan.jrxml");
            jasperDesign = JRXmlLoader.load(f);
            //param.clear();
            param.put("pesan.id_pesan", lbl_id.getText());
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, conn);
            jasperPrint.setName("Surat Jalan");
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(pstatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public String tgl1(String a){
        batas1=a;
        return a;
    }    
    public String tgl2(String a){
        batas2=a;
        return a;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_stat_cari;
    private javax.swing.JButton btn_stat_cek;
    private javax.swing.JButton btn_stat_fpesan;
    private javax.swing.JButton btn_stat_hapus;
    private javax.swing.JButton btn_stat_laporan;
    private javax.swing.JButton btn_stat_sjalan;
    private javax.swing.JButton btn_stat_ubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tbl_stat;
    private javax.swing.JTextField tf_stat_cari;
    // End of variables declaration//GEN-END:variables
}
